### ISSUE TITLE
Auto-refresh page

### ISSUE THREAD

**Issue by BrunoTeixeira1996** [TheMightyGit/rssole#37] opened 2023-07-27 09:40 UTC
It would be cool to auto-refresh the page in order to get the new feeds without needing to do it manualy.

Its simple as doing `<meta http-equiv="refresh" content="3" />` so maybe that would make sense to use.

**Comment by TheMightyGit** [comment] 2023-07-27 11:54
Dupe of #4

**Closed by TheMightyGit** 2023-07-27 11:54 UTC
